# Generated by Django 3.0.2 on 2020-02-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_restaurantsagra_restaurantsdelhi'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='img',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
