# Generated by Django 3.0.2 on 2020-02-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_restaurants_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsagra',
            name='img',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantsdelhi',
            name='img',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
