# Generated by Django 3.0.2 on 2020-02-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_milkbarrev'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milkbarrev',
            old_name='revowner',
            new_name='revowner1',
        ),
        migrations.AddField(
            model_name='milkbarrev',
            name='revowner2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
