# Generated by Django 3.0.2 on 2020-02-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20200207_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='GravityRev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev', models.TextField()),
                ('revowner1', models.CharField(max_length=100)),
                ('revowner2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KarimRev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev', models.TextField()),
                ('revowner1', models.CharField(max_length=100)),
                ('revowner2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SorrentoRev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev', models.TextField()),
                ('revowner1', models.CharField(max_length=100)),
                ('revowner2', models.CharField(max_length=100)),
            ],
        ),
    ]
